"""Application state: models and lookups loaded once at startup.

Why this matters: loading XGBoost models from disk and building a SHAP
explainer takes 1-3 seconds. If we did this per request, every API call
would be unbearably slow. Instead, we load everything once when the app
boots and hold it in memory for the life of the process.

FastAP's `lifespan` context manager is the modern way to do startup/shutdown
work. Older tutorials use `@app.on_event('startup')` - that API is deprecated.
"""
from __future__ import annotations

from contextlib import asynccontextmanager
from dataclasses import dataclass

import pandas as pd
import shap
from fastapi import FastAPI, HTTPException

from ..ml import config, models, recommender


@dataclass
class AppState:
    """Container for everything loaded at startup."""
    clv: models.CLVPredictor
    churn: models.ChurnPredictor
    churn_explainer: shap.TreeExplainer
    customers: pd.DataFrame
    feature_matrix: pd.DataFrame
    cross_sell_lookup: dict
    customer_top_product: pd.DataFrame
    clv_threshold: float
    
    
# Module-level state, populated by lifespan
state: AppState | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Run once at startup. Load models, features, predictions. lookups."""
    global state
    
    # Load trained models
    clv = models.CLVPredictor()
    churn = models.ChurnPredictor()
    
    # Pre-load the customer snapshot table. In production this would come from 
    # a database; for now we use the parquet generated by the training pipeline
    customers = pd.read_parquet(config.PROCESSED_DIR / 'customer_segments.parquet')
    
    # Prepare the feature matrix in the model's expected column order.
    df_enc = pd.get_dummies(customers, columns=['segment'], prefix='segment')
    feature_matrix = df_enc.copy()
    for col in churn.feature_names:
        if col not in feature_matrix.columns:
            feature_matrix[col] = 0
    feature_matrix = feature_matrix[churn.feature_names]
    
    # Predict everything once. (For a real system this would be a separate
    # batch job and the predictions would be persisted; for the demo, compute.)
    all_clv = clv.predict(customers)
    all_churn_risk = churn.predict_churn_risk(customers)
    customers = customers.assign(
        predicted_clv_90d = all_clv, churn_risk = all_churn_risk
    )
    
    # SHAP explainer is reusable across all customers.
    churn_explainer = recommender.get_shap_expalainer(churn.model)
    
    # CLV threshold for quadrant assignment.
    clv_threshold = recommender.compute_clv_threshold(customers['predicted_clv_90d'])
    
    # Cross-sell lookup
    cross_sell_lookup = recommender.load_cross_sell_lookup(
        config.PROCESSED_DIR / 'product_cross_sell.parquet'
    )
    
    # Per-customer "favorite product" lookup. Compute it once from 
    # the clean transaction if available; otherwise leave empty
    top_product_path = config.PROCESSED_DIR / 'customer_top_product.parquet'
    if top_product_path.exists():
        customer_top_product = pd.read_parquet(top_product_path).set_index('CustomerID')
    else:
        customer_top_product = pd.DataFrame()
        
    state = AppState(
        clv=clv,
        churn=churn,
        churn_explainer=churn_explainer,
        customers=customers,
        feature_matrix=feature_matrix,
        cross_sell_lookup=cross_sell_lookup,
        customer_top_product=customer_top_product,
        clv_threshold=clv_threshold
    )
    
    print(f'[lifespan] Ready: {len(customers):,} customers, '
          f'{len(cross_sell_lookup):,} products with cross-sell rules.')
    
    yield   # <- app runs while yielded
    
    # Shutdown cleanup (none needed for this app).
    print('[lifespan] Shutting down.')
    
    
def get_state() -> AppState:
    """Dependency: returns the loaded state, raising 503 if not yet ready."""
    if state is None:
        raise HTTPException(status_code=503, detail='Service is still starting up')
    return state